# cloudbuild.yaml (FINAL - Professional Build Structure)

steps:
  # STEP 0: Enable all required APIs for the project.
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    id: 'Enable APIs'
    entrypoint: 'gcloud'
    args:
      - 'services'
      - 'enable'
      - 'run.googleapis.com'
      - 'iam.googleapis.com'
      - 'sqladmin.googleapis.com'
      - 'firebase.googleapis.com'
      - 'secretmanager.googleapis.com'
      - 'artifactregistry.googleapis.com'
      - 'generativelanguage.googleapis.com'

  # STEP 1: Build the backend Docker image.
  - name: 'gcr.io/cloud-builders/docker'
    id: 'Build Backend'
    args:
      - 'build'
      - '--tag=${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_AR_REPO_NAME}/api-backend:latest'
      - '-f'
      - 'backend/Dockerfile'
      - '.'
    wait_for: ['Enable APIs']

  # STEP 2: Push the backend image.
  - name: 'gcr.io/cloud-builders/docker'
    id: 'Push Backend'
    args:
      - 'push'
      - '${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_AR_REPO_NAME}/api-backend:latest'
    wait_for: ['Build Backend']

  # STEP 3: Deploy the backend service to Cloud Run.
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    id: 'Deploy Backend'
    entrypoint: 'gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'api-backend'
      - '--image=${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_AR_REPO_NAME}/api-backend:latest'
      - '--region'
      - '${_REGION}'
      - '--allow-unauthenticated'
      - '--add-cloudsql-instances=${PROJECT_ID}:${_REGION}:hiring-platform-main-db'
      - '--update-secrets=DB_PASS=db-user-password:latest,GOOGLE_API_KEY=GOOGLE_API_KEY:latest'
      - '--set-env-vars=DB_USER=hiring_app_user,DB_NAME=hiring_platform_db,INSTANCE_CONNECTION_NAME=${PROJECT_ID}:${_REGION}:hiring-platform-main-db,GCP_PROJECT_ID=${PROJECT_ID},GCP_REGION=${_REGION}'
    wait_for: ['Push Backend']

  # --- THE FIX IS HERE ---
  # Use dedicated builders for each frontend task, the standard practice.

  # STEP 4: Install frontend node modules.
  - name: 'gcr.io/cloud-builders/npm'
    id: 'Frontend Install'
    args: ['install']
    dir: 'frontend'

  # STEP 5: Create the production build of the React app.
  - name: 'gcr.io/cloud-builders/npm'
    id: 'Frontend Build'
    args: ['run', 'build']
    dir: 'frontend'
    wait_for: ['Frontend Install']

  # STEP 6: Deploy the 'build' directory to Firebase Hosting.
  - name: 'gcr.io/cloud-builders/npm'
    id: 'Deploy Frontend'
    entrypoint: 'npm'
    args:
      - 'run'
      - 'deploy'
      - '--' # Separator for passing args to npm script
      - '--project=${PROJECT_ID}'
      - '--only=hosting'
    dir: 'frontend'
    wait_for: ['Frontend Build']


# Use the powerful service account you created for all steps.
service_account: 'projects/job-ai-c6f0a/serviceAccounts/hiring-ai@job-ai-c6f0a.iam.gserviceaccount.com'

# Define substitutions
substitutions:
  _REGION: 'us-central1'
  _AR_REPO_NAME: 'ai-hiring-platform-backend'

options:
  logging: CLOUD_LOGGING_ONLY