# cloudbuild.yaml (Definitive Final Version)

steps:
  # ---------------------------------------------------------------------------
  # STEP 0: THE FIX - Enable all required services for the pipeline to run.
  # This makes the pipeline self-sufficient and fixes the "permission denied" error.
  # ---------------------------------------------------------------------------
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'gcloud'
    args:
      - 'services'
      - 'enable'
      - 'containerregistry.googleapis.com' # The missing API for gcr.io
      - 'artifactregistry.googleapis.com'
      - 'cloudbuild.googleapis.com'
      - 'run.googleapis.com'
      - 'firebase.googleapis.com'
      - 'iam.googleapis.com'
    id: 'Enable APIs'

  # ---------------------------------------------------------------------------
  # STEP 1: Build the backend Docker image
  # ---------------------------------------------------------------------------
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - '${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_AR_REPO_NAME}/api-backend:latest'
      - './backend'
    id: 'Build Backend Image'
    wait_for: ['Enable APIs'] # Wait until APIs are enabled

  # ---------------------------------------------------------------------------
  # STEP 2: Push the backend Docker image
  # ---------------------------------------------------------------------------
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', '${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_AR_REPO_NAME}/api-backend:latest']
    id: 'Push Backend Image'

  # ---------------------------------------------------------------------------
  # STEP 3: Deploy the backend image to Cloud Run
  # ---------------------------------------------------------------------------
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'api-backend'
      - '--image=${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_AR_REPO_NAME}/api-backend:latest'
      - '--region'
      - '${_REGION}'
      - '--allow-unauthenticated'
    id: 'Deploy Backend to Cloud Run'

  # ---------------------------------------------------------------------------
  # STEP 4: Inject the backend URL into the frontend HTML
  # ---------------------------------------------------------------------------
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        BACKEND_URL=$$(gcloud run services describe api-backend --platform managed --region ${_REGION} --format 'value(status.url)')
        sed -i "s|YOUR_BACKEND_URL_WILL_GO_HERE|$${BACKEND_URL}|g" frontend/index.html
    id: 'Inject Backend URL'

  # ---------------------------------------------------------------------------
  # STEP 5: Deploy the frontend to Firebase Hosting
  # ---------------------------------------------------------------------------
  - name: 'gcr.io/firebase/firebase'
    args:
      - 'deploy'
      - '--project=${PROJECT_ID}'
      - '--only=hosting'
      - '--public=frontend'
      - '--non-interactive'
    id: 'Deploy Frontend to Firebase'

# Define substitutions for our variables
substitutions:
  _REGION: 'us-central1'
  _AR_REPO_NAME: 'ai-hiring-platform-backend'

options:
  logging: CLOUD_LOGGING_ONLY