# cloudbuild.yaml (FINAL - Self-Contained Frontend Build & Deploy)

steps:
  # STEP 0 & 1: Build and Push Backend (Working Correctly)
  - name: 'gcr.io/cloud-builders/docker'
    id: 'Build & Push Backend'
    args:
      - 'build'
      - '--tag=${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_AR_REPO_NAME}/api-backend:latest'
      - '--push=${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_AR_REPO_NAME}/api-backend:latest'
      - '-f'
      - 'backend/Dockerfile'
      - '.'

  # STEP 2: Deploy Backend (Working Correctly)
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    id: 'Deploy Backend'
    entrypoint: 'gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'api-backend'
      - '--image=${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_AR_REPO_NAME}/api-backend:latest'
      - '--region'
      - '${_REGION}'
      - '--allow-unauthenticated'
      - '--add-cloudsql-instances=${PROJECT_ID}:${_REGION}:hiring-platform-main-db'
      - '--update-secrets=DB_PASS=db-user-password:latest,GOOGLE_API_KEY=GOOGLE_API_KEY:latest'
      - '--set-env-vars=DB_USER=hiring_app_user,DB_NAME=hiring_platform_db,INSTANCE_CONNECTION_NAME=${PROJECT_ID}:${_REGION}:hiring-platform-main-db,GCP_PROJECT_ID=${PROJECT_ID},GCP_REGION=${_REGION}'
    wait_for: ['Build & Push Backend']

  # ---------------------------------------------------------------------------
  # STEP 3: THE FINAL FIX - A single, robust step for all frontend operations.
  # This installs all tools inside one environment to guarantee they are found.
  # ---------------------------------------------------------------------------
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    id: 'Build and Deploy Frontend'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        echo "INFO: Installing Node.js, npm, and Firebase Tools..."
        # Install curl, then use NodeSource to get a specific Node.js version
        apt-get update -y && apt-get install -y curl npm && \
        curl -sL https://deb.nodesource.com/setup_20.x | bash - && \
        apt-get install -y nodejs && \
        # Install Firebase Tools globally inside this step's environment
        npm install -g firebase-tools && \
        
        echo "INFO: Frontend tools installed. Starting build process..." && \
        # Go into frontend directory, install dependencies, build, and deploy
        cd frontend && \
        npm install && \
        npm run build && \
        firebase deploy --project=$PROJECT_ID --only=hosting --non-interactive
    wait_for: ['Deploy Backend']

# Use the powerful service account you created for all steps.
service_account: 'projects/job-ai-c6f0a/serviceAccounts/hiring-ai@job-ai-c6f0a.iam.gserviceaccount.com'

# Define substitutions
substitutions:
  _REGION: 'us-central1'
  _AR_REPO_NAME: 'ai-hiring-platform-backend'

options:
  logging: CLOUD_LOGGING_ONLY