# cloudbuild.yaml (FINAL - Professional Build Structure)

steps:
  # Build the backend Docker image
  - name: 'gcr.io/cloud-builders/docker'
    id: 'Build Backend'
    args:
      - 'build'
      - '--tag=<span class="math-inline">\{\_REGION\}\-docker\.pkg\.dev/</span>{PROJECT_ID}/<span class="math-inline">\{\_AR\_REPO\_NAME\}/api\-backend\:latest'
\- '\-f'
\- 'backend/Dockerfile'
\- '\.'
\# Push the backend image to Artifact Registry
\- name\: 'gcr\.io/cloud\-builders/docker'
id\: 'Push Backend'
args\: \['push', '</span>{_REGION}-docker.pkg.dev/<span class="math-inline">\{PROJECT\_ID\}/</span>{_AR_REPO_NAME}/api-backend:latest']
    wait_for: ['Build Backend']

  # Deploy the backend service to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    id: 'Deploy Backend'
    entrypoint: 'gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'api-backend'
      - '--image=<span class="math-inline">\{\_REGION\}\-docker\.pkg\.dev/</span>{PROJECT_ID}/<span class="math-inline">\{\_AR\_REPO\_NAME\}/api\-backend\:latest'
\- '\-\-region'
\- '</span>{_REGION}'
      - '--allow-unauthenticated'
      - '--add-cloudsql-instances=<span class="math-inline">\{PROJECT\_ID\}\:</span>{_REGION}:hiring-platform-main-db'
      - '--update-secrets=DB_PASS=db-user-password:latest'
    wait_for: ['Push Backend']

  # Install frontend dependencies
  - name: 'gcr.io/cloud-builders/npm'
    id: 'Frontend Install'
    args: ['install']
    dir: 'frontend'

  # Build the React application
  - name: 'gcr.io/cloud-builders/npm'
    id: 'Frontend Build'
    args: ['run', 'build']
    dir: 'frontend'
    wait_for: ['Frontend Install']

  # Deploy the frontend to Firebase Hosting
  - name: 'gcr.io/firebase/firebase'
    id: 'Deploy Frontend'
    args:
      - 'deploy'
      - '--project=${PROJECT_ID}'
      - '--only=hosting'
      - '--non-interactive'
    dir: 'frontend'
    wait_for: ['Frontend Build']

# Use the powerful service account you created for all steps.
service_account: 'projects/job-ai-c6f0a/serviceAccounts/hiring-ai@job-ai-c6f0a.iam.gserviceaccount.com'

# Define substitutions
substitutions:
  _REGION: 'us-central1'
  _AR_REPO_NAME: 'ai-hiring-platform-backend'

options:
  logging: CLOUD_LOGGING_ONLY