# cloudbuild.yaml (FINAL - Simplified and Corrected)

steps:
  # STEP 0: Run Terraform to provision/verify infrastructure.
  - name: 'hashicorp/terraform:1.5.7'
    id: 'Terraform Init and Apply'
    entrypoint: 'sh'
    args:
      - '-c'
      - |
        cd infrastructure
        terraform init
        terraform apply -auto-approve -var="gcp_project_id=${PROJECT_ID}"

  # STEP 1: Build the backend Docker image.
  - name: 'gcr.io/cloud-builders/docker'
    id: 'Build Backend'
    args:
      - 'build'
      - '--tag=us-central1-docker.pkg.dev/${PROJECT_ID}/ai-hiring-platform-backend/api-backend:latest'
      - '-f'
      - 'backend/Dockerfile'
      - '.'
    wait_for: ['Terraform Init and Apply']

  # STEP 2: Push the backend image.
  - name: 'gcr.io/cloud-builders/docker'
    id: 'Push Backend'
    args: ['push', 'us-central1-docker.pkg.dev/${PROJECT_ID}/ai-hiring-platform-backend/api-backend:latest']
    wait_for: ['Build Backend']

  # STEP 3: Deploy the backend service to Cloud Run.
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    id: 'Deploy Backend'
    entrypoint: 'gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'api-backend'
      - '--image=us-central1-docker.pkg.dev/${PROJECT_ID}/ai-hiring-platform-backend/api-backend:latest'
      - '--region=us-central1'
      - '--allow-unauthenticated'
      - '--service-account=hiring-ai@${PROJECT_ID}.iam.gserviceaccount.com'
      - '--add-cloudsql-instances=${PROJECT_ID}:us-central1:hiring-platform-main-db'
      - '--update-secrets=DB_PASS=db-user-password:latest,GOOGLE_API_KEY=GOOGLE_API_KEY:latest'
      - '--set-env-vars=DB_USER=hiring_app_user,DB_NAME=hiring_platform_db,INSTANCE_CONNECTION_NAME=${PROJECT_ID}:us-central1:hiring-platform-main-db'
    wait_for: ['Push Backend']

  # STEP 4: Build and Deploy the Frontend (Simplified)
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    id: 'Build and Deploy Frontend'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        apt-get update -y && apt-get install -y curl nodejs npm
        npm install -g firebase-tools
        cd frontend
        npm install
        npm run build
        # THE FIX: Authenticate using the service account, not a token.
        firebase deploy --project=$PROJECT_ID --only=hosting --non-interactive
    wait_for: ['Deploy Backend']

# This ensures all steps run as your powerful service account.
service_account: 'projects/hiringagent/serviceAccounts/hiring-ai@hiringagent.iam.gserviceaccount.com'

options:
  logging: CLOUD_LOGGING_ONLY