

steps:
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    id: 'Enable APIs'
    entrypoint: 'gcloud'
    args: ['services','enable','containerregistry.googleapis.com','artifactregistry.googleapis.com','cloudbuild.googleapis.com','run.googleapis.com','firebase.googleapis.com','iam.googleapis.com','secretmanager.googleapis.com', 'aiplatform.googleapis.com', 'generativelanguage.googleapis.com']

  - name: 'gcr.io/cloud-builders/docker'
    id: 'Build Backend Image'
    args: ['build','--tag=<span class="math-inline">\{\_REGION\}\-docker\.pkg\.dev/</span>{PROJECT_ID}/<span class="math-inline">\{\_AR\_REPO\_NAME\}/api\-backend\:latest','\-f','backend/Dockerfile','\.'\]
wait\_for\: \['Enable APIs'\]
\- name\: 'gcr\.io/cloud\-builders/docker'
id\: 'Push Backend Image'
args\: \['push', '</span>{_REGION}-docker.pkg.dev/<span class="math-inline">\{PROJECT\_ID\}/</span>{_AR_REPO_NAME}/api-backend:latest']
    wait_for: ['Build Backend Image']

  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    id: 'Deploy Backend to Cloud Run'
    entrypoint: 'gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'api-backend'
      - '--image=<span class="math-inline">\{\_REGION\}\-docker\.pkg\.dev/</span>{PROJECT_ID}/<span class="math-inline">\{\_AR\_REPO\_NAME\}/api\-backend\:latest'
\- '\-\-region'
\- '</span>{_REGION}'
      - '--allow-unauthenticated'
      - '--add-cloudsql-instances=<span class="math-inline">\{PROJECT\_ID\}\:</span>{_REGION}:hiring-platform-main-db'
      # THE FIX IS HERE: Pass the Google API Key as a secret
      - '--update-secrets=DB_PASS=db-user-password:latest,GOOGLE_API_KEY=GOOGLE_API_KEY:latest'
      - '--set-env-vars=DB_USER=hiring_app_user,DB_NAME=hiring_platform_db,INSTANCE_CONNECTION_NAME=<span class="math-inline">\{PROJECT\_ID\}\:</span>{_REGION}:hiring-platform-main-db,GCP_PROJECT_ID=<span class="math-inline">\{PROJECT\_ID\},GCP\_REGION\=</span>{_REGION}'
    wait_for: ['Push Backend Image']

  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    id: 'Build and Deploy Frontend'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        apt-get update > /dev/null && apt-get install -y nodejs npm
        npm install -g firebase-tools
        cd frontend
        npm install
        npm run build
        firebase deploy --project=$PROJECT_ID --only=hosting --non-interactive
    wait_for: ['Deploy Backend to Cloud Run']

substitutions:
  _REGION: 'us-central1'
  _AR_REPO_NAME: 'ai-hiring-platform-backend'

options:
  logging: CLOUD_LOGGING_ONLY