INFO 2025-07-03T17:21:39.314827458Z Finished Step #0 - "Terraform Init and Apply"
INFO 2025-07-03T17:21:39.314998758Z ERROR
  {
    "textPayload": "ERROR",
    "insertId": "6866381a-155b-423f-a264-60a48874d92f-345",
    "resource": {
      "type": "build",
      "labels": {
        "build_trigger_id": "b61bc1d7-9edb-422c-85d1-11bcd0396427",
        "build_id": "6866381a-155b-423f-a264-60a48874d92f",
        "project_id": "hiringagent"
      }
    },
    "timestamp": "2025-07-03T17:21:39.314998758Z",
    "severity": "INFO",
    "labels": {
      "build_step": "MAIN",
      "build_tags": "trigger-b61bc1d7-9edb-422c-85d1-11bcd0396427"
    },
    "logName": "projects/hiringagent/logs/cloudbuild",
    "receiveTimestamp": "2025-07-03T17:21:39.494659955Z"
  }
INFO 2025-07-03T17:21:39.315037101Z ERROR: build step 0 "hashicorp/terraform:1.5.7" failed: step exited with non-zero status: 1
  {
    "textPayload": "ERROR: build step 0 \"hashicorp/terraform:1.5.7\" failed: step exited with non-zero status: 1",
    "insertId": "6866381a-155b-423f-a264-60a48874d92f-346",
    "resource": {
      "type": "build",
      "labels": {
        "build_trigger_id": "b61bc1d7-9edb-422c-85d1-11bcd0396427",
        "project_id": "hiringagent",
        "build_id": "6866381a-155b-423f-a264-60a48874d92f"
      }
    },
    "timestamp": "2025-07-03T17:21:39.315037101Z",
    "severity": "INFO",
    "labels": {
      "build_tags": "trigger-b61bc1d7-9edb-422c-85d1-11bcd0396427",
      "build_step": "MAIN"
    },
    "logName": "projects/hiringagent/logs/cloudbuild",
    "receiveTimestamp": "2025-07-03T17:21:39.494659955Z"
  }
